//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid Tutorial1 = new Guid("92cbf7ce-7e45-4fb0-9bca-b10db358b779");

    }
}
